app/profile/__init__.py
from flask import Blueprint

bp = Blueprint('profile', __name__)

from app.profile import routes

app/profile/routes.py
#https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login#step-1-installing-packages
from flask import render_template, redirect, url_for, request, flash, jsonify, session, current_app
from flask_principal import Identity, identity_changed
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash
from app.profile import bp
from app.main.utils import pretty_time, calculate_refund_amount, get_days_until_departure
from app.models import User, Bookings, Listings
from app.logger import auth_logger
from app import db, permission_required, user_permission

@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    #If a callback URL has been sent in any request add it to the session, once user signed up it will be handled and return
    #the user to the previous page they were browsing (does not currently hold a full page cache)
    if request.args.get('callback'):
        session['callback'] = request.args.get('callback')

    if request.method == 'POST':
        form_data = {
            'email': request.form.get('email'),
            'username': request.form.get('username'),
            'password': request.form.get('password')
        }

        # Validate form data
        error = validate_signup_form(form_data)
        if error:
            flash(error, 'error')
            return redirect(url_for('profile.signup'))

        # Create new user and log in automatically
        try:
            new_user = User.create_user(
                username=form_data['username'],
                email=form_data['email'],
                password=form_data['password']
            )
            db.session.add(new_user)
            db.session.commit()

            remember = True if request.form.get('remember') else False
            login_user(new_user, remember=remember)
            
            # User identity has changed, need to force update
            identity_changed.send(current_app._get_current_object(), identity=Identity(new_user.id))

            if 'callback' in session.keys():
                callback = session.pop('callback')
                flash("Account successfully created. Please review your booking before continuing", 'success')
                return redirect(callback)
            
            flash('Successfully created your account. You have been logged in automatically', 'success')
            return redirect(url_for('profile.index'))
        except Exception as e:
            auth_logger.error(f"Unable to create user: {e}")
            flash('An error occurred. Please try again.', 'error')
            return redirect(url_for('profile.signup'))

    return render_template('profile/signup.html')

def validate_signup_form(form_data):
    if not all(form_data.values()):
        return 'Missing required fields: Email, Username, Password'

    if not is_valid_username(form_data['username']):
        return "You are only allowed to use the following special characters in usernames: - _ +"

    if User.search_user_by_email(form_data['email']):
            return'Email address already exists'

    if User.search_user_by_username(form_data['username']):
        return 'Username already exists'
    
    return None

def is_valid_username(username):
    allowed_special_chars = "-_+"
    return all(c.isalnum() or c in allowed_special_chars for c in username)


@bp.route('/login', methods=['POST'])
def login_post():
    username_field = request.form.get('username')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False # Change to boolean value depending if tickbox is selected

    if '@' in username_field:
        user = User.search_user_by_email(username_field)
    else:
        user = User.search_user_by_username(username_field)

    if not user or not check_password_hash(user.password, password):
        flash('Invalid username/email and or password. Please try again or <a href="' + url_for('profile.password_reset') + '">reset your password here</a>.', 'danger')
        return redirect(url_for('profile.login'))

    login_user(user, remember=remember)

    identity_changed.send(current_app._get_current_object(), identity=Identity(user.id))

    if 'callback' in session.keys():
        callback = session.pop('callback')
        flash("You have been successfully logged in. Please review your booking before continuing", 'success')
        return redirect(callback)
    
    return redirect(url_for('profile.index'))


@bp.route('/check-username', methods=['POST'])
def check_username():
    data = request.get_json()
    username = data.get('username', '').strip()
    if username is None:
        return jsonify({'error': 'Username is required'}), 400
    
    if not is_valid_username(username):
        return jsonify({'error': "Username contains invalid special characters. You may only use: - _ +"}), 400
    #Search to see if username already exists
    user_exist = User.search_user_by_username(username)
    if user_exist is not None:
        return jsonify({'error': 'Username already exists'}), 400

    return jsonify({'available': True, 'success': username + ' is available.'})


@bp.route('/check-email', methods=['POST'])
def check_email():
    data = request.get_json()
    email = data.get('email', '').strip()

    if email is None:
        return jsonify({'error': 'Email is required'}), 400
    
    email_exist = User.search_user_by_email(email)

    if email_exist:
        return jsonify({'error': 'Email already registered'}), 400

    return jsonify({'available': True, 'success': 'Email is available'})


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@bp.route('/login')
def login():
    #If a callback URL has been sent in any request add it to the session, once user logged in it will be handled and return
    #the user to the previous page they were browsing (does not currently hold a full page cache)
    if request.args.get('callback'):
        session['callback'] = request.args.get('callback')
    if current_user.is_authenticated:
        return redirect(url_for('profile.index'))

    return render_template('profile/login.html')


@bp.route('/password-reset')
def password_reset():
    return render_template('profile/password-reset.html')


@bp.route('/password-reset', methods=['POST'])
def check_password_reset_1():
    username = request.form.get('username')
    email = request.form.get('email')
    
    #Search to see if username already exists
    user_exist = User.search_user_by_username(username)
    if user_exist is None:
        return flash('Username does not exist', 'error')
    
    email_exist = User.search_user_by_email(email)
    if email_exist is None:
        return flash('Email does not exist', 'error')

    session['password-reset-email'] = email
    return redirect(url_for('profile.password_reset_2'))


@bp.route('/password-reset/2FA')
def password_reset_2():
    return render_template('profile/password-reset-2.html')


@bp.route('/password-reset/2FA', methods=['POST'])
def check_password_reset_2():
    code =  request.form.get('2fa-code')
    
    #Simulate 2FA code being entered
    if code == '123456' or code == '234567':
        return redirect(url_for('profile.password_reset_3'))
    
    return flash('Invalid 2FA Code', 'error')


@bp.route('/password-reset/reset-password')
def password_reset_3():
    return render_template('profile/password-reset-3.html')


@bp.route('password-reset/from-profile')
@permission_required(user_permission)
def password_reset_from_profile():
    email = current_user.email


@bp.route('/password-reset/reset-password', methods=['POST'])
def password_reset_process():
    email = session.get('password-reset-email')
    
    if email == None:
        email = current_user.email
        
    password1 = request.form.get('password-1')
    password2 = request.form.get('password-2')
    
    #Simulate 2FA code being entered
    if password1 == password2:
        User.change_user_password(email, password1)
        flash('Password was updated successfully', 'success')
        return redirect(url_for('profile.login'))
    flash('Passwords must match', 'error')
    return redirect(url_for('profile.password_reset_3'))

@login_required
@bp.route('/home')
def index():
    if current_user.is_authenticated:
        return render_template('profile/index.html', username=current_user.username)
    
    return redirect(url_for('profile.login'))

@login_required
@bp.route('/manage_bookings')
def manage_bookings():
    if current_user.is_authenticated:
        bookings = Bookings.get_user_bookings(current_user.id)
        locations = Listings.get_all_locations(True)
        return render_template('profile/manage_bookings.html', username=current_user.username, bookings=bookings, locations=locations)
    
    flash('You must be logged in to view your current bookings', 'error')
    return redirect(url_for('profile.login'))

@bp.route('/manage_profile', methods=['GET', 'POST'])
def manage_profile():
    user = User.search_user_id(current_user.id)

    if user == None:
        flash('You must be logged in to update your profile','error')
        return redirect(url_for('main.index'))
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        
        User.update_user_details(user.id, username, email)
        
        flash('Successfully updated profile details', 'success')
        return redirect(url_for('profile.manage_profile'))
    return render_template('profile/manage_profile.html', user=user)


@bp.route('/manage_bookings/view/<int:id>')
def manage_profile_view_booking(id):
    if not Bookings.check_booking_user_ids_match(id, current_user.id):
        flash('The booking you are trying to access is not associated with your account.', 'error')

app/templates/profile/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron mt-5">
        <h1 class="display-4">Hello, {{username.capitalize()}}!</h1>
        <p class="lead">Welcome to your Horizon Travels dashboard. Your next travel date is on the horizon!</p>
        <hr class="my-4">
    </div>
    <div class="row mt-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Manage Bookings</h5>
                    <p class="card-text">Easily view and update your bookings.</p>
                    <a href="{{ url_for('profile.manage_bookings') }}" class="btn btn-primary">Go to Bookings</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Update Personal Information</h5>
                    <p class="card-text">Keep your personal details up to date.</p>
                    <a href="{{ url_for('profile.manage_profile') }}" class="btn btn-secondary">Update Info</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/login.html
{% extends 'base.html' %}
{% block content %}
<div class="column is-4 is-offset-4">
    <div id="login-box" class="form_box_30" style="margin-top: 30px;">
        <div class="profile_form_background">
            <h2 class="form_header">Login</h2>
            <form method="POST" action="{{ url_for('profile.login_post') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="mb-3">
                    <label class="form-label" autofocus="">Username/Email</label>
                    <input type="text" class="form-control" name="username">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="mb-3">
                    <a class="clear-hyperlink" href="{{ url_for('profile.password_reset') }}">Forgot Password?</a>
                </div>
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="remember" name="remember">
                    <label class="form-check-label" for="remember">Remember me</label>
                </div>
                <button type="submit" class="btn btn-primary">Log In</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/manage_bookings.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-4">
    <div class="d-flex justify-content-between mb-3">
        <h2>Manage Bookings</h2>
        <div>    
            <button type="button" class="btn btn-primary me-2" data-bs-toggle="modal" data-bs-target="#filterModal">
                <i class="fa-solid fa-filter"></i> Filter
            </button>
        </div>
    </div>
    
    <div class="table-container">
        <table id="manage_bookings" class="table table-striped table-bordered display hover" style="width:100%">
            <thead>
                <tr>
                    <th>Booking ID</th>
                    <th>Booking Date</th>
                    <th>Departure Date</th>
                    <th>Departure Location</th>
                    <th>Destination Location</th>
                    <th>Cancelled</th>
                    <th>View Booking</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in bookings %}
                <tr>
                    <td>{{ booking.id }}</td>
                    <td>{{ booking.booking_date }}</td>
                    <td>{{ booking.departure_date }}</td>
                    <td>{{ booking.departure_location }}</td>
                    <td>{{ booking.destination_location }}</td>
                    <td>{{ 'Yes' if booking.cancelled else 'No' }}</td>
                    <td class="dt-center">
                        <a class="btn btn-secondary view-booking-btn" href="manage_bookings/view/{{ booking.id }}">View Booking</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Filter modal -->
    <div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="filterModalLabel"><i class="fa-solid fa-filter"></i> Filter Options</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="filter-form">
                        <div class="mb-3">
                            <label for="depart_location" class="form-label">Depart Location:</label>
                            <select class="form-control select2-multiple" id="depart_location" name="depart_location[]" multiple="multiple">
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="destination_location" class="form-label">Destination Location:</label>
                            <select class="form-control select2-multiple" id="destination_location" name="destination_location[]" multiple="multiple">
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="depart_date" class="form-label">Depart Date:</label>
                            <input type="date" class="form-control" id="depart_date" name="depart_date">
                        </div>
                        <div class="mb-3">
                            <label for="booking_date" class="form-label">Booking Date:</label>
                            <input type="date" class="form-control" id="booking_date" name="booking_date">
                        </div>
                        <div class="mb-3">
                            <label for="exclude_cancelled" class="form-label">Exclude Cancelled:</label>
                            <input type="checkbox" class="form-check-input" id="exclude_cancelled" name="exclude_cancelled">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="apply-filters">Apply Filters</button>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .table-container {
        width: 100%;
        overflow-x: auto;
        overflow-y: hidden;
    }

    @media (max-width: 800px) {
        .table-container {
            padding: 0 10px;
        }
    }

    .dataTables_wrapper {
        width: 100%;
    }

    table.dataTable.no-footer {
        margin-bottom: 30px;
    }
</style>
<script>
    $(document).ready(function() {
        $('.select2-multiple').select2({
            placeholder: "Select locations",
            width: '100%'
        });

        $('.select2-dropdown').select2({
            placeholder: "Select a date",
            width: '100%',
            minimumResultsForSearch: Infinity
        });

        const locations = JSON.parse('{{ locations|tojson|safe }}');
        locations.forEach(location => {
            $('#depart_location').append(new Option(location, location));
            $('#destination_location').append(new Option(location, location));
        });

        // Load table
        const table = $('#manage_bookings').DataTable({
            pageLength: 10,
            lengthChange: false,
            searching: false,
            ordering: false,
            ajax: {
                url: "{{ url_for('bookings.get_user_bookings') }}",
                dataSrc: '',
                data: function(d) {
                    d.depart_location = $('#depart_location').val() ? $('#depart_location').val().join(',') : '';
                    d.destination_location = $('#destination_location').val() ? $('#destination_location').val().join(',') : '';
                    d.depart_date = $('#depart_date').val();
                    d.booking_date = $('#booking_date').val();
                    d.exclude_cancelled = $('#exclude_cancelled').is(':checked');
                }
            },
            columns: [
                { data: 'id', visible: false }, // Hidden id column
                { data: 'booking_date' },
                { data: 'depart_date' },
                { data: 'depart_location' },
                { data: 'destination_location' },
                { data: 'cancelled' },
                {
                    data: null,
                    className: "dt-center",
                    defaultContent: `
                        <a class="btn btn-secondary view-booking-btn" href="#">View Booking</a>
                    `
                }
            ],
            language: {
                emptyTable: "No bookings could be found."
            },
            createdRow: function(row, data, dataIndex) {
                $(row).find('.view-booking-btn').attr('href', `manage_bookings/view/${data.id}`);
            }
        });

        $('#apply-filters').on('click', function() {
            table.ajax.reload();
            $('#filterModal').modal('hide');
        });
    });
</script>
{% endblock %}

app/templates/profile/manage_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h1 class="display-4 mb-4">User Profile</h1>
    <form id="updateForm" action="{{ url_for('profile.manage_profile') }}" method="post" onsubmit="return showModal()">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" disabled required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" disabled required>
        </div>
        <button type="submit" class="btn btn-primary d-none mt-3" id="updateButton">Update Info</button>
    </form>
    <div class="d-flex justify-content-start mt-3">
        <button class="btn btn-dark mr-3" id="editButton" style="margin-right:10px" onclick="enableEditing()">
            <i class="fas fa-wrench"></i> Edit
        </button>
        <a href="{{ url_for('profile.password_reset_process') }}" class="btn btn-warning ml-2"><i class="fas fa-key"></i> Reset Password</a>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel">Confirm Update</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Type "CONFIRM" to proceed with the update.</p>
                <input type="text" class="form-control" id="confirmInput" required>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="hideModal()">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="submitForm()">Confirm</button>
            </div>
        </div>
    </div>
</div>
<script>
    function enableEditing() {
        document.getElementById('username').disabled = false;
        document.getElementById('email').disabled = false;
        document.getElementById('updateButton').classList.remove('d-none');
    }

    function showModal() {
        $('#confirmModal').modal('show');
        return false;
    }

    function hideModal() {
        $('#confirmModal').modal('hide');
    }

    function submitForm() {
        var confirmInput = document.getElementById('confirmInput').value;
        if (confirmInput === 'CONFIRM') {
            document.getElementById('updateForm').submit();
        } else {
            alert('Please type "CONFIRM" to proceed.');
        }
    }
</script>
{% endblock %}

app/templates/profile/password-reset-2.html
{% extends 'base.html' %}

{% block content %}
<div class="form_box_30 background_1">
    <div class="profile_form_background">
        <h3 class="form_header">2FA Code</h3>
        <form method="POST" action="{{ url_for('profile.check_password_reset_2') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="mb-3">
                <label class="form-label" for="2fa-code" autofocus="">Enter 2FA Code</label>
                <input type="text" id="2fa-code" class="form-control" name="2fa-code" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit 2FA</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/profile/password-reset-3.html
{% extends 'base.html' %}

{% block content %}
<div class="form_box_30 background_1">
    <div class="profile_form_background">
        <h3 class="form_header">Password Reset</h3>
        <form method="POST" action="{{ url_for('profile.password_reset_process') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="mb-3">
                <label class="form-label" for="password-1" autofocus="">Enter your new password</label>
                <input type="text" id="password-1" class="form-control" name="password-1" required>
            </div>
            <div class="mb-3">
                <label class="form-label" for="password-2" autofocus="">Re-enter your new password</label>
                <input type="text" id="password-2" class="form-control" name="password-2" required>
            </div>
            <button type="submit" class="btn btn-primary">Update Password</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/profile/password-reset.html
{% extends 'base.html' %}

{% block content %}
<div class="form_box_30 background_1">
    <div class="profile_form_background">
        <h3 class="form_header">Password Reset</h3>
        <form method="POST" action="{{ url_for('profile.check_password_reset_1') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="mb-3">
                <label class="form-label" for="username" autofocus="">Username</label>
                <input type="text" id="username" class="form-control" name="username" required>
                <small id="username-feedback" class="form-text"></small>
            </div>
            <div class="mb-3">
                <label class="form-label" for="email">Email address</label>
                <input type="email" id="email" class="form-control" name="email" required>
                <small id="email-feedback" class="form-text"></small>
            </div>
            <button type="submit" class="btn btn-primary">Reset Password</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/profile/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="form_box_30 background_1">
    <div class="profile_form_background">
        <h3 class="form_header">Sign Up</h3>
        <form method="POST" action="{{ url_for('profile.signup') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="mb-3">
                <label class="form-label" for="username" autofocus="">Username</label>
                <input type="text" id="username" class="form-control" name="username" required>
                <small id="username-feedback" class="form-text"></small>
            </div>
            <div class="mb-3">
                <label class="form-label" for="email">Email address</label>
                <input type="email" id="email" class="form-control" name="email" required>
                <small id="email-feedback" class="form-text"></small>
            </div>
            <div class="mb-3">
                <label class="form-label" for="password">Password</label>
                <input type="password" id="password" class="form-control" name="password" required>
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="remember" name="remember">
                <label class="form-check-label" for="remember">Remember me</label>
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
    </div>
</div>

<script>
    function makeAjaxRequest(url, data, field) {
        const feedbackElement = document.getElementById(`${field}-feedback`);
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

        feedbackElement.textContent = '';
        feedbackElement.style.color = '';

        if (data[field].length > 0) {
            fetch(url, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrfToken,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(data),
            })
                .then(response => response.json())
                .then(data => {
                    if (data.available) {
                        feedbackElement.textContent = data.success;
                        feedbackElement.style.color = 'green';
                    } else {
                        feedbackElement.textContent = data.error;
                        feedbackElement.style.color = 'red';
                    }
                })
                .catch(error => {
                    feedbackElement.textContent = `Error checking ${field}.`;
                    feedbackElement.style.color = 'red';
                });
        }
    }

    function checkUsernameAvailability(username) {
        makeAjaxRequest("{{ url_for('profile.check_username') }}", { 'username': username }, 'username');
    }

    function checkEmailAvailability(email) {
        makeAjaxRequest("{{ url_for('profile.check_email') }}", { 'email': email }, 'email');
    }

    function delayAvailabilityCheck(func, delay) {
        let timer;
        return function(...args) {
            clearTimeout(timer);
            timer = setTimeout(() => func.apply(this, args), delay);
        };
    }

    document.getElementById('username').addEventListener('input', delayAvailabilityCheck(function () {
        checkUsernameAvailability(this.value);
    }, 500));

    document.getElementById('email').addEventListener('input', delayAvailabilityCheck(function () {
        const emailValue = this.value;
        if (emailValue.includes('@') && emailValue.includes('.')) {
            checkEmailAvailability(this.value);
        }
    }, 500));

</script>
{% endblock %}